card/urls.py
from django.urls import path,re_path
from . import views

from django.views.generic.base import TemplateView
urlpatterns = [
    #path('<int:pk>',TemplateView.as_view(template_name='flashcard/card.html'), name='card'),
    path('',TemplateView.as_view(template_name='flashcard/card.html'), name='card'),
    
    path('<slug:slug>/<int:known>/',views.detail,name="lexicon"),
    path('quiz/<slug:slug>/<int:id>/',views.take_quiz,name="quiz"),
    
]

vocabulary/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.views.generic.base import TemplateView
from card.views import addCustomizeWord,listCustomizeWord,deleteCustomizeWord,setPlan
#import auth
urlpatterns = [

    path('admin/', admin.site.urls),
   
    path('l_cust_word/', listCustomizeWord, name='list_all'),
    
    path('delete/<slug:slug>/', deleteCustomizeWord, name='delete'),

    path('main/',setPlan,name='home'),

    path('', TemplateView.as_view(template_name='home.html'), name='main'),

    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    re_path(r'^card/',include('card.urls')),
    


]

card/models.py
from django.db import models
import account

# Create your models here.
class Word(models.Model):
	word=models.CharField('单词',max_length=50,null=False,primary_key=True)  
	meaning=models.CharField('释义',max_length=200,null=False)
	phonetic=models.CharField('音标',max_length=100,null=False)
	belong=models.CharField('所属词典',max_length=100,null=False)
	class Meta:
		unique_together=("word","belong")
	#time_modified=models.DateField(auto_now=True)

class Lexicon(models.Model):
	name=models.CharField(max_length=200,primary_key=True,default='anonomous') #belong to which list  name=<username>+<wordlist>
	words=models.ManyToManyField(Word, related_name='lexicon')


class CustomizedLexicon(models.Model):
	user=models.ForeignKey(account.models.CustomUser,on_delete=models.CASCADE,related_name='custword')
	word=models.ForeignKey(Word,on_delete=models.CASCADE)
	class Meta:
		unique_together=("user","word")


def validate_range(value):
    if value<0:  # Your desired conditions here
        raise ValidationError('%s some error message' % value)



class UserPlan(models.Model):
	user=models.OneToOneField(account.models.CustomUser,on_delete=models.CASCADE,related_name='userplan',null=False,primary_key=True)  
	amount=models.IntegerField(default=50,validators=[validate_range])

class UserLexicon(models.Model):
	user=models.ForeignKey(account.models.CustomUser,on_delete=models.CASCADE,related_name='userword')
	lexicon=models.ManyToManyField(Word, through='UserWordList')

class UserWordList(models.Model):
	user=models.ForeignKey(UserLexicon,on_delete=models.CASCADE)
	word=models.ForeignKey(Word,on_delete=models.CASCADE)
	is_new=models.BooleanField(default=True)
	count=models.IntegerField(default=0,validators=[validate_range])   #count=10为记住，越小越出现概率越大
	date_modified = models.DateTimeField(auto_now=True)
	date_created = models.DateTimeField(auto_now_add=True)

card/forms.py
#-*- coding: utf-8 -*-
from django import forms
from .models import Lexicon,CustomizedLexicon
from django.utils.translation import gettext
from django.core.exceptions import ValidationError
def validate_excel(value):
	if value.name.split('.')[-1] not in ['xls','xlsx']:
		raise ValidationError('Invalid File Type!Must be execel')


class LexiconForm(forms.Form):
	name=forms.CharField(max_length=200)
	lexicon = forms.FileField(validators=[validate_excel])
	class Meta:
   		model=Lexicon
   		fields=('name','lexicon')
'''
class CustomizedLexiconForm(forms.Form):
	words = forms.FileField(validators=[validate_excel])
	class Meta:
   		model=CustomizedLexicon
   		fields=('user','words')
'''

class CustomizedWordForm(forms.Form):
	new_word=forms.CharField(label='输入单词',max_length=50,required=True) 
	new_meaning=forms.CharField(label='含义',max_length=200,required=True)
	new_phonetic=forms.CharField(label='音标',max_length=100,required=True)

templates/base.html
 <!-- templates/base.html -->
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
    <title>{% block title %}词说{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
   
    <link href="{% static 'bootstrap4-fs-modal/dist/css/bootstrap-fs-modal.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/blue.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.12.1/bootstrap-table.min.css">
    <link rel="stylesheet" href="{% static 'css/code.css' %}"/>
  
    {% block head %} {% endblock%}

    
    
  </head>
  <body >

    <nav class="navbar navbar-expand-md navbar-dark bg-primary mb-4">
      <a href="/main/" class="navbar-header logo1" >词说</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <!-- 修改密码 + log out-->
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change' %}">修改密码</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">登出</a>
                <div class="dropdown-divider"></div>
                
                <a class="dropdown-item" data-toggle="modal" data-target="#myModal">
                  设置计划
                </a>

            </li>

                <!-- 上传词典文件 -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">
                          输入每日背单词量(0~200)
                        </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                          &times;
                        </button>
                      </div>
                      
                      <form class="" method="post" enctype="multipart/form-data" >
                      <div class="modal-body">
                        {% csrf_token %}
                        <p>学习计划
                        <input id="id_plan" name="plan" type="number" min="0" max="200" onKeyUp="this.value=this.value.replace(/[^\.\d]/g,'');this.value=this.value.replace('.','');">
                        </p>
                        
                        {%if saved %}
                         <p>成功上传!</p>
                        {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                        </button>
                        <input type="submit"  class="btn btn-success ml-2" value="设置">
                      </div>
                      </form>
                    
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal -->
                </div>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-light my-2 my-sm-0">Log in</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
    {% block content %}

    {% endblock %}
    <p class="mt-5 mb-3 text-muted">&copy; 2018 by Cherie</p>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/icheck.js' %}"></script>

    {% block script %}
    {% endblock %}
  </body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">学习计划</h4>
          </div>
          <div id='plan_info' class="text-hide">恭喜你已经完成今日学习任务！</div>
          <div class="card-body">
          <p class="text-muted">今日已学习</p>
            <h1 class="card-title pricing-card-title">{{learn_num}} <small class="text-muted">/ {{ plan_num }}</small></h1>
            <ul class="list-unstyled mt-3 mb-4">
              <li>好好学习</li>
              <li>天天向上</li>
            </ul>

            <button type="button" class="btn btn-lg btn-block btn-outline-primary"  data-toggle="modal" data-target="#modalBottom">修改计划</button>
          </div>
        </div>
</li>

                <!-- 上传词典文件 -->
                <div class="modal fade modal-fullscreen modal-fullscreen-bottom-footer" id="modalBottom" tabindex="-1" role="dialog" aria-labelledby="modalBottomLabel" aria-hidden="true">

                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">
                          输入每日背单词量(0~200)
                        </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          &times;
                        </button>
                      </div>
                      <form action="{% url 'home' %}" class="" method="post" enctype="multipart/form-data" >
                      <div class="modal-body">
                        {% csrf_token %}
                        <p>学习计划
                        <input id="id_plan" name="plan" type="number" min="0" max="200" onKeyUp="this.value=this.value.replace(/[^\.\d]/g,'');this.value=this.value.replace('.','');">
                        </p>
                        {%if saved_plan == 1 %}
                         <script type="text/javascript">alert("Successfully Set!")</script>
                        {% endif %}
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal" value="关闭">
                        </button>
                        <input type="submit"  class="btn btn-success ml-2" value="设置">
                      </div>
                      </form>
                    
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal -->
                </div>
          </ul>
{%endif %}

<div class="jumbotron p-3 p-md-3 text-white rounded bg-success">
	<div class="col-md-8 px-0">
		<h1 class="logo">
			词说
		</h1 >

		{% if user.is_authenticated %}
    <h3 class="prompt">
		  Hi {{ user.username }}!
    </h3>
		{% else %}

		  <h3 class="prompt my-3">Create an account to save your progress.It's free and only takes a minute!</p>
		  </h3><a href="{% url 'signup' %}" class="btn btn-primary ml-2">注册用户</a>
		  	or
		  	<a href="{% url 'login' %}">登录</a>

		  </p>

	</div>
	
</div>
{% endif %}
<!-- 触发模态窗口的按钮 -->



{% if user.is_authenticated %}


<div>
	<div class="card border-info mb-3">
			  <img class="card-img-top" src="../static/img/cust_word.png" alt="Card image cap">

			  <div class="card-body text-info">
			    <h5 class="card-title">My Own words</h5>
			    <p class="card-text">Manage Your Own words here!</p>
			    <a href="{% url 'list_all' %}" class="btn btn-info">Check all</a>
			    <a class="btn btn-outline-secondary" data-toggle="modal" data-target="#myModal1" >Add Word</a>
			    
			  </div>
	</li>

                <!-- 上传词汇-->
                <div class="modal fade modal-fullscreen modal-fullscreen-bottom-footer" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="modalBottomLabel" aria-hidden="true">

                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          &times;
                        </button>
                        <h4 class="text-primary" id="myModalLabel1" >
                          Upload Your Own Word
                        </h4>
                      </div>
                      <form action="" class="" method="post" enctype="multipart/form-data"  onSubmit="return beforeSubmit(this);">
                      <div class="modal-body">
                        {% csrf_token %}

                        <p class="text-muted">词汇
                        <input id="id_name" name="new_word" type="text">
                        </p>
                        <p class="text-muted">含义
                        <input id="id_meaning" name="new_meaning" type="text">
                        </p >
                        <p class="text-muted">音标
                        <input id="id_phonetic" name="new_phonetic" type="text">
                        </p>
                        
                        {%if saved == 1 %}
                         <script type="text/javascript">alert("Successfully Upload!")</script>
                        
                        {%elif saved == 0 %}
                        	<script type="text/javascript">alert("This word already existed!")</script>
                        {% endif %}

                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                        </button>
                        <input type="submit"  class="btn btn-success ml-2" value="添加" onclick="validation()">
                      </div>
                      </form>

                    
                    </div><!-- /.modal-content -->
                  </div><!-- /.modal -->
                </div>



          </ul>
	</div>

	<div class="card border-danger mb-3">
			  <img class="card-img-top" src="../static/img/toefl.png" alt="Card image cap">

			  <div class="card-body text-danger">
			    <h5 class="card-title">Tofel words 1</h5>
			    <p class="card-text">托福基本词汇</p>
			    <a href="{% url 'lexicon' slug='toefl' known=2 %}" class="btn btn btn-danger">Practice this deck</a>
			    <a href="{% url 'quiz' slug='toefl' id='0' %}" class="btn btn-outline-secondary">Quiz</a>

			  </div>
	</div>
	<div class="card border-success mb-3">
			  <img class="card-img-top" src="../static/img/gre.png" alt="Card image cap">

			  <div class="card-body text-success">
			    <h5 class="card-title">GRE words 2</h5>
			    <p class="card-text">GRE核心词汇</p>
			    <a href="{% url 'lexicon' slug='gre' known=2 %}" class="btn btn-success">Practice this deck</a>
			    <a href="{% url 'quiz' slug='gre' id='0' %}" class="btn btn-outline-secondary">Quiz</a>
			  </div>
	</div>

</div>

{% else %}
<div></div>
{% endif %}

{% endblock %}

{% block script %}
<script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>  
   <script type="text/javascript">
  
var main = function(){ 
	if({{learn_num}}<{{plan_num}}){
		$('#plan_info').attr('class','text-hide');
	}
	else{
		$('#plan_info').attr('class','alert alert-success');
	}
 };
$(document).ready(main);

function beforeSubmit(form){
  var reg=/^[a-zA-Z]*$/;
  if(!reg.test(form.new_word.value))
  {
    alert("只能输入字母！");
    form.new_word.focus();
    return false;
  }
  if(form.new_word.value==''){
    alert('单词不能为空！');
    form.new_word.focus();
    return false;
  }
  if(form.new_word.value.length>30){
    alert('单词过长');
    form.new_word.focus();
    return false;
  }
  if(form.new_meaning.value.length>30){
    alert('释义过长');
    form.new_meaning.focus();
    return false;
  }
  if(form.new_phonetic.value.length>30){
    alert('音标过长');
    form.new_phonetic.focus();
    return false;
  }

  if(form.new_meaning.value==''){
    alert('释义不能为空');
    form.new_meaning.focus();
    return false;
  }
  if(form.new_phonetic.value.length<6){
    alert('音标不能为空');
    form.new_phonetic.focus();
    return false;
  }
  
  return true;
}



 </script> 



{% endblock %}